app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/',array('as'=>'index','uses'=>'UsersController@loginForm'));
Route::get('/login',array('as'=>'login.form','uses'=>'UsersController@loginForm'));
Route::post('/',array('as'=>'login.action','uses'=>'UsersController@loginAction'));
Route::get('/logout',array('as'=>'logout','uses'=>'UsersController@logout'));
Route::get('/panel',array('as'=>'panel','uses'=>'UsersController@panel'));
Route::get('/resend', array('as'=>'users.resendConfEmailForm', 'uses' => 'UsersController@resendConfEmailForm'));
Route::post('/resend', array('as'=>'users.resendConfEmailAction', 'uses' => 'UsersController@resendConfEmailAction'));
Route::get('/forget', array('as'=>'users.forgetPasswordForm', 'uses' => 'UsersController@forgetPasswordForm'));
Route::post('/forget', array('as'=>'users.forgetPasswordAction', 'uses' => 'UsersController@forgetPasswordAction'));
Route::get('/forgetConfirm/{token}', array('as'=>'users.forgetPasswordConfirmForm', 'uses' => 'UsersController@forgetPasswordConfirmForm'));
Route::post('/forgetConfirm/{token}', array('as'=>'users.forgetPasswordConfirmAction', 'uses' => 'UsersController@forgetPasswordConfirmAction'));

Route::get('/fotFound',array('as' => 'notFound','uses' => 'UsersController@notFound'));
Route::get('/permissionsDenied',array('as' => 'permissionsDenied','uses' => 'UsersController@permissionsDenied'));
Route::get('/visitorOnly',array('as' => 'visitorOnly','uses' => 'UsersController@visitorOnly'));

Route::resource('users', 'UsersController');
Route::put('/users/{id}/changeEmail',array('as'=>'users.updateEmail', 'uses' => 'UsersController@updateEmail'));
Route::put('/users/{id}/changePassword',array('as'=>'users.updatePass', 'uses' => 'UsersController@updatePass'));
Route::put('/users/{id}/changeDetails',array('as'=>'users.updateDetails', 'uses' => 'UsersController@updateDetails'));

Route::resource('sponsors', 'SponsorsController');
Route::delete('/sponsors/{id}/activate',array('as'=>'sponsors.activate','uses'=>'SponsorsController@activate'));
Route::delete('/sponsors/{id}/{pid}/suspend',array('as'=>'sponsors.suspend','uses'=>'SponsorsController@suspend'));
Route::get('/sponsors/join/{url}',array('as'=>'sponsors.join','uses'=>'SponsorsController@join'));
Route::post('/sponsors/register/{url}',array('as'=>'sponsors.register','uses'=>'SponsorsController@register'));
Route::get('/sponsors/{hash}/confirm',array('as'=>'sponsors.confirm','uses'=>'SponsorsController@confirm'));
Route::get('/mySponsors',array('as'=>'mySponsors','uses'=>'SponsorsController@mySponsors'));
Route::get('/sponsors/{id}/projects',array('as'=>'sponsors.projects','uses'=>'SponsorsController@projects'));

Route::resource('recipients', 'RecipientsController');
Route::get('/join/{url}',array('as'=>'recipients.join','uses'=>'RecipientsController@join'));
Route::post('/recipients/register/{url}',array('as'=>'recipients.register','uses'=>'RecipientsController@register'));
Route::get('/recipients/of/{id}',array('as'=>'recipients.perProject','uses'=>'RecipientsController@perProject'));
Route::post('/recipients/{id}/accept',array('as'=>'recipients.accept','uses'=>'RecipientsController@accept'));
Route::post('/recipients/{id}/deny',array('as'=>'recipients.deny','uses'=>'RecipientsController@deny'));
Route::get('/recipients/{hash}/confirm',array('as'=>'recipients.confirm','uses'=>'RecipientsController@confirm'));
Route::get('/myRecipients',array('as'=>'myRecipients','uses'=>'RecipientsController@myRecipients'));

Route::resource('coordinators', 'CoordinatorsController');
Route::get('/coordinators/{id}/projects',array('as'=>'projects.perCoordinator','uses'=>'ProjectsController@perCoordinator'));

Route::resource('projects', 'ProjectsController');
Route::get('/projects/{id}/sponsors',array('as'=>'sponsors.perProject','uses'=>'SponsorsController@perProject'));
Route::get('/projects/{id}/recipients',array('as'=>'recipients.perProject','uses'=>'RecipientsController@perProject'));
Route::delete('/projects/{id}/withdraw',array('as'=>'projects.withdraw','uses'=>'ProjectsController@withdraw'));
Route::delete('/projects/{id}/close',array('as'=>'projects.close','uses'=>'ProjectsController@close'));
Route::delete('/projects/{id}/open',array('as'=>'projects.open','uses'=>'ProjectsController@open'));
Route::get('/myProject',array('as'=>'myProject','uses'=>'ProjectsController@myProject'));
Route::get('/joinProject',array('as'=>'joinProject','uses'=>'ProjectsController@joinProject'));
Route::get('/joinProject/{id}',array('as'=>'joinProjectAction','uses'=>'ProjectsController@joinProjectAction'));

Route::resource('payments', 'PaymentsController');
Route::get('/myTransactions',array('as'=>'myTransactions','uses'=>'PaymentsController@myTransactions'));
Route::get('/payments/add/{pid}/{uid}',array('as'=>'payments.add','uses'=>'PaymentsController@add'));
Route::get('/payments/request/{pid}/{uid}',array('as'=>'payments.request','uses'=>'PaymentsController@request'));
Route::post('/payments/save/{pid}/{uid}',array('as'=>'payments.save','uses'=>'PaymentsController@save'));
Route::delete('/payments/accept/{pid}',array('as'=>'payments.accept','uses'=>'PaymentsController@accept'));
Route::delete('/payments/reject/{pid}',array('as'=>'payments.reject','uses'=>'PaymentsController@reject'));

Route::resource('projects.invitations', 'InvitationsController');
Route::resource('settings', 'SettingsController');
Route::resource('projects.spends', 'SpendsController');
Route::get('/myActivities',array('as'=>'myActivities','uses'=>'SpendsController@myActivities'));

Route::get('/daily-cron',function(){
    return Cron::run();
});

app/models/Project.php
<?php

class Project extends \LaravelBook\Ardent\Ardent {
	protected $guarded = array();
	public static $rules = array(
        'name' => 'required|min:3|unique:projects',
        'content' =>'required',
        'max_recipients' => 'required|numeric',
        'max_sponsors_per_recipient' => 'required|numeric',
        'currency' => 'required',
        'amount' => 'required|numeric',
        'euro_amount' => 'required|numeric',
        'gf_commission' => 'required|numeric'
    );
    protected $fillable = array('name','content','max_recipients','max_sponsors_per_recipient','currency','amount','euro_amount','gf_commission');
    public $autoHydrateEntityFromInput = true;    // hydrates on new entries' validation
    public $forceEntityHydrationFromInput = true; // hydrates whenever validation is called

    public static $relationsData = array(
        'coordinator' => array(self::HAS_ONE, 'Coordinator'),
        'recipients' => array(self::HAS_MANY, 'Recipient'),
        'sponsors' => array(self::BELONGS_TO_MANY, 'Sponsor','project_sponsor'),
        'invitations' => array(self::HAS_MANY, 'Invitation'),
        'payments' => array(self::HAS_MANY, 'Payment'),
        'spends' => array(self::HAS_MANY, 'Spend')
    );

    public function hasSponsorPlace(){
        foreach ($this->recipients as $recipient){
            if($recipient->confirmed){
                if(is_null($recipient->sponsors))
                    return true;
                else{
                    $count = $recipient->sponsors->count();
                    // foreach ($recipient->sponsors as $sponsor){
                    //     if($sponsor->hasNotPaid($this->id))
                    //         $count --;
                    // }
                    if($count < $this->max_sponsors_per_recipient)
                        return true;
                }
            }
        }
        return false;
    }

    // Recipients:
    public function getFreeRecipient(){
        foreach ($this->recipients as $recipient){
            if($recipient->confirmed &&
                (is_null($recipient->sponsors) || $recipient->sponsors->count() < $this->max_sponsors_per_recipient))
                return $recipient->id;
        }
        return false;
    }

    // Sponsors:
    public function paymentsOfSponsor($sid){
        return Sponsor::find($sid)->paymentsOfProject($this->id);
    }

    public function recipientOfSponsor($sid){
        return Sponsor::find($sid)->recipientOfProject($this->id);
    }

    public function confirmedPaymentsOfSponsor($sid){
        return $this->paymentsOfSponsor($sid)->where('stat','=','accepted');
    }
    // public function notPaidBy($sid){
    //     if(count($this->ConfirmedPaymentsBy($sid)) == 0)
    //         return true;
    //     return false;
    // }

    public function getMaxSponsorsNumber(){
        $recipients = $this->recipients;
        $max = 0;
        foreach ($recipients as $recipient){
            if($recipient->sponsors->count() > $max)
                $max = $recipient->sponsors->count();
        }
        return $max;
    }

}

app/controllers/ProjectsController.php
<?php
class ProjectsController extends BaseController{

    public function __construct(){
        $this->beforeFilter('auth',array('only'=> array( 
            'index', 'myProject', 'create', 'store', 'show', 'edit', 'update', 'close', 'open', 'joinProject', 'joinProjectAction', 'withdraw'
        )));
    }

    public function index(){
        $projects = Project::all();
        $this->render('projects.index','Projects',array('projects'=>$projects));
    }

    public function joinProject(){
        $accountType = Auth::user()->account_type;
        if($accountType != 'Sponsor') return Redirect::route('notFound');
        $sponsorProjectsIds = Auth::user()->account->projects->lists('id');
        if(empty($sponsorProjectsIds))
            $projects = Project::where('open','=',true)->get();
        else
            $projects = Project::whereNotIn('id',$sponsorProjectsIds)->where('open','=',true)->get();
        $this->render('projects.sponsor_join','Join A Project',array(
            'projects' => $projects
        ));
    }

    public function joinProjectAction($pid){
        $accountType = Auth::user()->account_type;
        $project = Project::find($pid);
        if($accountType != 'Sponsor') return Redirect::route('permissionsDenied');
        if(is_null($project)) return Redirect::route('notFound');
        $sponsor = Auth::user()->account;

        $rid = $project->getFreeRecipient();
        if($rid){
            DB::table('project_sponsor')->insert(array(
                'sponsor_id' => $sponsor->id,
                'recipient_id' => $rid,
                'project_id' => $project->id
            ));

            $recipient = Recipient::find($rid);

            $payment = new Payment;
            $payment->project_id = $project->id;
            $payment->sender_id = $sponsor->user->id;
            $payment->receiver_id = $recipient->user->id;
            $payment->type = "sponsoring";
            $payment->stat = "pending";
            $payment->save();

            Mail::send('emails.sponsors.joining', array(
                    'name'=>$sponsor->name,
                    'id'=>$sponsor->id,
                    'project' => $project,
                    'recipientSkrill' => $recipient->skrill_acc
                ), function($message){
                $message->to(Auth::user()->email)->subject('Thank you for joining new project');
            });

            Session::put('success','You have joined the project "'.$project->name.'" Please check your email inbox to make your first payment !');
            return Redirect::route('joinProject');
        }else{
            Session::put('error','There is no empty place on this peoject currently. Please retry later ');
            return Redirect::route('joinProject');
        }
    }

    public function myProject(){
        $user = Auth::user();
        switch($user->account_type){
            case 'Admin' :
                return Redirect::route('projects.index');
            break;
            case 'Coordinator' :
                $project = Project::find($user->account->project_id);
                $this->render('projects.show',$project->name,array(
                    'project' => $project
                ));
            break;
            case 'Recipient' :
                $project = Project::find($user->account->project_id);
                $sponsors = $user->account->sponsors;
                $this->render('projects.show',$project->name,array(
                    'project' => $project,
                    'sponsors' => $sponsors
                ));
            break;
            case 'Sponsor' :
                $this->render('projects.index','My Projects',array(
                    'projects' => $user->account->projects
                ));
            break;
        }
    }

    public function create(){
        $this->render('projects.create','Add new project');
    }

    public function store(){
        $project = new Project;
        $project->url = str_replace(" ", "_", strtolower(e(Input::get('name'))));
        $project->open = true;
        $coordinator = new Coordinator;
        $user = new User;

        $user->account_type = 'Coordinator';
        User::$rules['password'] = 'required|min:6';

        if($project->save()){
            if($user->save()){
                $coordinator->project_id = $project->id;
                $coordinator->user_id = $user->id;
                $coordinator->save();
                Session::put('success','Project has been added !');
                return Redirect::route('projects.show',$project->url);
            }else{
                $project->delete();
                Session::put('error','There were some errors !');
                return Redirect::route('projects.create')->withErrors($user->errors())->withInput();
            }
        }else{
            Session::put('error','There were some errors !');
            if($user->save()) $user->delete();
            return Redirect::route('projects.create')->withErrors($project->errors())->withInput();
        }
    }

    public function show($url){
        $project = Project::where('url','=',$url)->first();
        if(is_null($project)){
            return Redirect::route('notFound');
        }else{
            $this->render('projects.show','Project: '.$project->name,array('project'=>$project));
        }
    }

    public function edit($url){
        $project = Project::where('url','=',$url)->first();
        if(is_null($project)){
            return Redirect::route('notFound');
        }else{
            $this->render('projects.edit','Edit: '.$project->name,array('project'=>$project));
        }
    }

    public function update($id){
        $project = Project::find($id);
        Project::$rules['name'] = 'required|min:3|unique:projects,name,'.$id;
        $project->url = str_replace(" ", "_", strtolower(e(Input::get('name'))));
        //... checking if max recipients and max sponsors entered are not less then current ones !!
        if($project->save()){
            Session::put('success','Project editted successfully !');
            return Redirect::route('projects.show',$project->url);
        }else{
            Session::put('error','There were some errors !');
            return Redirect::route('projects.edit',$project->url)->withErrors($project->errors())->withInput();
        }
    }


    public function close($id){
        $project = Project::find($id);
        $project->open = false;
        $project->forceSave();
        Session::put('error','The project \''.$project->name.'\' has been closed !');
        return Redirect::route('projects.index');
    }

    public function open($id){
        $project = Project::find($id);
        $project->autoHydrateEntityFromInput = false;    
        $project->forceEntityHydrationFromInput = false; 
        $project->open = true;
        $project->forceSave();
        Session::put('success','The project \''.$project->name.'\' has been opened !');
        return Redirect::route('projects.index');
    }

    public function withdraw($id){
        $accountType = Auth::user()->account_type;
        $project = Project::find($id);
        if($accountType != 'Sponsor') return Redirect::route('permissionsDenied');
        if(is_null($project)) return Redirect::route('notFound');
        $sponsor = Auth::user()->account;

        DB::table('project_sponsor')->where('sponsor_id','=',$sponsor->id)
            ->where('project_id', '=', $id)
            ->delete();
        
        Session::put('info','You don\'t sponsorise the project "'.$project->name.'" anymore. You can still rejoin the project later if you want.');
        return Redirect::route('myProject');
    }
}

app/views/projects/coordinator_show.blade.php
<h2>Informations: </h2>
<div class="infos">
    <p class="field">Name :</p><p class="value">{{ $project->name }}</p><div class="clear"></div>
    <p class="field">Recipients Number :</p><p class="value">{{ $project->recipients->count() }}</p><div class="clear"></div>
    <p class="field">Sponsors Number :</p><p class="value">{{ $project->sponsors->count() }}</p><div class="clear"></div>
    <p class="field">Sponsors Registration link:</p><p class="value">{{ URL::route('sponsors.join',$project->url) }}</p><div class="clear"></div>
    <p class="field">Amount :</p><p class="value">{{ $project->amount }} in {{ $project->currency }} (approx {{ $project->euro_amount }} Euro) </p><div class="clear"></div>
    <p class="field">Fund Group amount :</p><p class="value">{{ $project->gf_commission }} in {{ $project->currency }}</p><div class="clear"></div>
</div>

<h2>Recipients: </h2><?php $recipients = $project->recipients; ?>
@include('recipients.index')

<h2>Sponsors: </h2><?php $sponsors = $project->sponsors; ?>
@include('sponsors.index')

<h2>Payments: </h2><?php $payments = $project->payments; $profileAccountType = 'Coordinator'; ?>
@include('payments.index')

app/views/projects/create.blade.php
{{ Form::open(array('route'=>'projects.store')) }}

    {{ Form::label('name','Project name :'), Form::text('name',Input::old('name')) }}
        @if($errors->has('name')) {{ $errors->first('name','<p class="remarques"> :message </p>') }} @endif
        <div class="clear"></div> 

    {{ Form::label('max_recipients',' Max recipients number :'), Form::text('max_recipients',Input::old('max_recipients')) }}
    @if($errors->has('max_recipients')) {{ $errors->first('max_recipients','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('max_sponsors_per_recipient',' Max sponsors per recipient :'), Form::text('max_sponsors_per_recipient',Input::old('max_sponsors_per_recipient')) }}
    @if($errors->has('max_sponsors_per_recipient')) {{ $errors->first('max_sponsors_per_recipient','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('currency',' Currency :'), Form::text('currency',Input::old('currency')) }}
    @if($errors->has('currency')) {{ $errors->first('currency','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('amount',' Amount :'), Form::text('amount',Input::old('amount')) }}
    @if($errors->has('amount')) {{ $errors->first('amount','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('euro_amount',' Amount in euro :'), Form::text('euro_amount',Input::old('euro_amount')) }}
    @if($errors->has('euro_amount')) {{ $errors->first('euro_amount','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('gf_commission',' group fund amount :'), Form::text('gf_commission',Input::old('gf_commission')) }}
    @if($errors->has('gf_commission')) {{ $errors->first('gf_commission','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>
    {{ Form::label('username',' Coordinator\'s username :'), Form::text('username',Input::old('username')) }}
    @if($errors->has('username')) {{ $errors->first('username','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>
    {{ Form::label('email',' Coordinator\'s email :'), Form::text('email',Input::old('email')) }}
    @if($errors->has('email')) {{ $errors->first('email','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>
    {{ Form::label('password',' Coordinator\'s password :'), Form::text('password',Input::old('password')) }}
    @if($errors->has('password')) {{ $errors->first('password','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>
    {{ Form::label('content','Content :')}} 
        <div class="clear"></div>
    {{ Form::textarea('content',Input::old('content'),array('class'=>'ckeditor full')) }} 
        @if($errors->has('content')) {{ $errors->first('content','<p class="remarques"> :message </p>') }} @endif
        <div class="clear"></div>

{{ Form::submit('Add'), Form::close() }}

app/views/projects/edit.blade.php
{{ Form::model($project,array('route'=>array('projects.update',$project->id), 'method'=>'put')),
    Form::label('name','Project name :'), Form::text('name') }}
        @if($errors->has('name')) {{ $errors->first('name','<p class="remarques"> :message </p>') }} @endif
        <div class="clear"></div> 

    {{ Form::label('max_recipients',' Max recipients number :'), Form::text('max_recipients') }}
    @if($errors->has('max_recipients')) {{ $errors->first('max_recipients','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('max_sponsors_per_recipient',' Max sponsors per recipient :'), Form::text('max_sponsors_per_recipient') }}
    @if($errors->has('max_sponsors_per_recipient')) {{ $errors->first('max_sponsors_per_recipient','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('currency',' Currency :'), Form::text('currency') }}
    @if($errors->has('currency')) {{ $errors->first('currency','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('amount',' Amount :'), Form::text('amount') }}
    @if($errors->has('amount')) {{ $errors->first('amount','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('euro_amount',' Amount in euro :'), Form::text('euro_amount') }}
    @if($errors->has('euro_amount')) {{ $errors->first('euro_amount','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>

    {{ Form::label('gf_commission',' group fund amount :'), Form::text('gf_commission') }}
    @if($errors->has('gf_commission')) {{ $errors->first('gf_commission','<p class="remarques"> :message </p>') }} @endif
    <div class="clear"></div>
    {{ Form::label('content','Content :')}} 
        <div class="clear"></div>
    {{ Form::textarea('content',$project->content,array('class'=>'ckeditor full')) }} 
        @if($errors->has('content')) {{ $errors->first('content','<p class="remarques"> :message </p>') }} @endif
        <div class="clear"></div>
{{ Form::submit('Save'), Form::close() }}

app/views/projects/index.blade.php
<?php $accountType = Auth::user()->account_type; ?>
<script>
function ConfirmDelete()
{
  var x = confirm("Please note that by withdrawing, you will cease to be a sponsor for this project. You can rejoin this project again.");
  if (x)
    return true;
  else
    return false;
}
</script>
@if($accountType == 'Admin')
<a style="float: left; margin-left: 30px;" href="{{ URL::route('projects.create') }}" class="add_item  button">New Project</a>
@endif
@if(!count($projects)) <table> @else <table class="data"> @endif 
    <thead><tr>
        <th colspan="3">Project</th>
        @if($accountType == 'Sponsor')
        <th colspan="2">Recipient</th>
        @else
        <th colspan="2">Coordinator</th>
        @endif
        <th></th>
    </tr></thead>
<thead><tr>
        <th>Name</th>
        <th>Recipients</th>
        <th>Sponsors</th>
        @if($accountType == 'Sponsor')
        <th>Name</th>
        <th>Skrill ID</th>
        @else
        <th>Coordinator</th>
        @endif
        <th></th>
    </tr></thead>
    <tbody>
    @if(!count($projects))
    <tr>
        <td colspan="5"><p>There is no projects yet ! </p></td>
    </tr>
    @endif
    @foreach($projects as $project)
    <tr>
        <td>{{$project->name}}</td>
        <td>{{$project->recipients->count()}}</td>
        <td>{{$project->sponsors->count()}}</td>
        @if($accountType == 'Sponsor')
        <td>{{$project->recipientOfSponsor(Auth::user()->account->id)->user->username}}</td>
        <td>{{$project->recipientOfSponsor(Auth::user()->account->id)->skrill_acc}}</td>
        @else
        <td>{{$project->coordinator->user->username}}</td>
        @endif        
        <td>
            <a href="{{ URL::route('projects.show',$project->url) }}" class="button">Details</a>
            <a href="{{ URL::route('projects.spends.index',$project->id) }}" class="button"> Activities </a>
        @if($accountType == 'Sponsor')
            {{ Form::open(array('class'=>'inline', 'method'=>'delete','route'=>array('projects.withdraw',$project->id), 'onsubmit' => 'return ConfirmDelete()')),
                Form::submit('Withdraw',['class' => 'red_button']),
            Form::close() }}
        @endif
        @if($accountType == 'Admin')
            <a href="{{ URL::route('projects.invitations.index',$project->id) }}" class="button">Invitations</a>
            <a href="{{ URL::route('projects.edit',$project->url) }}" class="orange_button">Edit</a>
            @if($project->open)
            {{ Form::open(array('class'=>'inline', 'method'=>'delete','route'=>array('projects.close',$project->id))),
                Form::submit('Close'),
            Form::close() }}
            @else
            {{ Form::open(array('class'=>'inline', 'method'=>'delete','route'=>array('projects.open',$project->id))),
                Form::submit('Reopen'),
            Form::close() }}
            @endif
        @endif
        </td>
    </tr>
    @endforeach
</tbody></table>

app/views/projects/show.blade.php
<?php $accountType = Auth::user()->account_type; ?>

@if($accountType == 'Recipient')
<h2>Recipient Information: </h2>
@include('recipients.info')
@endif


<?php // Payments showen only for Admin ?>
@if($accountType == 'Admin')
<h2>Payments: </h2><?php $payments = $project->payments; $profileAccountType = 'Admin'; ?>
@include('payments.index')
@endif

@if($accountType == 'Admin' || $accountType == 'Coordinator')
<h2>Recipients: </h2><?php $recipients = $project->recipients; ?>
@include('recipients.index')
@endif



@if($accountType == 'Recipient')
<h2>Sponsors: </h2>
@include('sponsors.index')
@elseif($accountType != 'Sponsor')
<h2>Sponsors: </h2><?php $sponsors = $project->sponsors; ?>
@include('sponsors.index')
@endif

<h2>Project Informations: </h2>
<div class="infos">
    <p class="field">Name :</p><p class="value">{{ $project->name }}</p><div class="clear"></div>
    @if($accountType == 'Admin')
    <p class="field">Coordinator username :</p><p class="value">{{ $project->coordinator->user->username }}</p><div class="clear"></div>
    <p class="field">Coordinator email :</p><p class="value"> {{ $project->coordinator->user->email }} </p><div class="clear"></div>
    @endif
    <p class="field">Recipients Number :</p><p class="value">{{ $project->recipients->count() }}</p><div class="clear"></div>
    <p class="field">Sponsors Number :</p><p class="value">{{ $project->sponsors->count() }}</p><div class="clear"></div>
    <p class="field">Sponsors Registration link:</p><p class="value">{{ URL::route('sponsors.join',$project->url) }}</p><div class="clear"></div>
    <p class="field">Amount :</p><p class="value">{{ $project->amount }} in {{ $project->currency }} (approx {{ $project->euro_amount }} Euro) </p><div class="clear"></div>
    <p class="field">Fund Group amount :</p><p class="value">{{ $project->gf_commission }} in {{ $project->currency }}</p><div class="clear"></div>
    @if($accountType == 'Admin')
    <div class="links">
        <a href="{{URL::route('projects.edit',$project->url)}}">Edit Project</a>
        @if($project->open)
        {{ Form::open(array('class'=>'inline', 'method'=>'delete','route'=>array('projects.close',$project->id))),
        Form::submit('Close'),
        Form::close() }}
        @else
        {{ Form::open(array('class'=>'inline', 'method'=>'delete','route'=>array('projects.open',$project->id))),
        Form::submit('Reopen'),
        Form::close() }}
        @endif
    </div>
    @endif
</div>

<h2>Project Activities: </h2><?php $spends = $project->spends; ?>
@include('spends.index')

app/views/projects/sponsor_join.blade.php
@if(!count($projects)) <table> @else <table class="data"> @endif 
    <thead><tr>
        <th>Name</th>
        <th>Amount</th>
        <th>Currency</th>
        <th></th>
    </tr></thead>
    <tbody>
    @if(!count($projects))
    <tr>
        <td colspan="4"><p>There are no projects yet! </p></td>
    </tr>
    @endif
    @foreach($projects as $project)
    <tr>
        <td>{{$project->name}}</td>
        <td>{{$project->amount}}</td>
        <td>{{$project->currency}}</td>
        <td>
            <a href="{{ URL::route('projects.show',$project->url) }}" class="button">Details</a>
            <?php if($project->hasSponsorPlace()):?><a href="{{URL::route('joinProjectAction',$project->id)}}" class="button">Join this project </a><?php endif;?>
        </td>
    </tr>
    @endforeach
</tbody></table>